import numpy as np

def load_team_data(flatten=True):
    # Load the processed data generated by preprocess.py
    X_train = np.load('data/processed/X_train_cnn.npy')
    X_test = np.load('data/processed/X_test_cnn.npy')
    y_train = np.load('data/processed/y_train.npy')
    y_test = np.load('data/processed/y_test.npy')

    if flatten:
        # For logistic regression and random forest: (samples, 32, 32, 1) -> (samples, 1024)
        X_train = X_train.reshape(X_train.shape[0], -1)
        X_test = X_test.reshape(X_test.shape[0], -1)
    
    # For CNN: (samples, 32, 32, 1)
    return X_train, X_test, y_train, y_test